DOP-1702 build metadata for k8s
seniorlink-vela/gh-action-common pull request #9
Opened 2022-03-15 18:45 UTC by tlarocque

*Commits*
- 48759b8 - dont need to change build-secrets
- 6fd8ab8 - try: change to token
- 7be8a5b - cleaning up
- 2252814 - commit msgs dont work well
- bd37f2c - must quote generic string data
- 8e95194 - fixing quotes
- 1e21a85 - updating tags and labels
- 7d6e5ff - wip: testing addl labels and tags
- 15b7b3a - modifying tag generation rules
- 0f1997d - add registry to base image specifier
- e95d556 - remove custom tags for now
- 1b0f3ac - input should be github token
- d2f4d26 - image name not automatically detected
- e91de7a - base image name required
- 7053e73 - try: first set of tags and labels

2022-03-16 18:10 UTC, zswanson commented on composite/docker-build/action.yml
> +          org.opencontainers.image.revision=apple${{ steps.short-sha.outputs.sha }}
`revision=apple` ??

2022-03-16 18:12 UTC, zswanson requested changes
Looks like you had a testing/verification output stuck in the labels that needs to be removed

2022-03-16 18:22 UTC, tlarocque commented on composite/docker-build/action.yml
> +          org.opencontainers.image.revision=apple${{ steps.short-sha.outputs.sha }}
yeah I was testing appending lol.  Forgot to push the revert

2022-03-18 17:10 UTC, jonasoneves approved these changes

2022-03-21 15:00 UTC, merged